### ISSUE TITLE
Tailwind JIT doesn't notice classNames in stories and the doc

### ISSUE THREAD

**Issue by aymenmensi** [divriots/backlight.dev#16]
### Reproduction steps

1. Go to Carousel component
2. Click on Stories 
3. try in edit mode to add css classes

### Current Behavior

when I right CSS classNames in the stories they don't work 

### Expected Behavior

when I right CSS classNames in the stories they should be compiled and work

### Link to the design system

https://backlight.dev/preview/9LQ2g0NXwPXvlTjjqowY/Carousel?branch=~carousel@fQoRetAV7CYcsvagVNrhMZI5sMw1

### What browser(s) are you seeing the problem on?

Chrome

**Comment by gqio** [comment]
Hi Aymen,

I’m on it.
Thanks for reporting it.

I’ll keep you posted.
Best

**Comment by gqio** [comment]
Hello Aymen,

This issue has been fixed and released.

Please report if you encounter any issue.
Thanks again for reporting it

Best,
