### ISSUE TITLE
Documentation site: CTRL+K focuses omnibar in Windows / Chrome (instead of the search field)

### ISSUE THREAD

**Issue by kaelig** [divriots/backlight.dev#21]
### 📖 Reproduction steps

In Windows 11, using Chrome:

1. Go to https://backlight.dev/docs
2. Hit <kbd>CTRL</kbd> + <kbd>K</kbd>

### 🙁 Current Behavior

Focus quickly moves to the search field, and then the Omnibar ("Search Google").

### 🙂 Expected Behavior

Focus moves to the search field.

### 🌐 What browser(s) are you seeing the problem on?

Chrome

### Browser version(s)

98

**Comment by jorenbroekema** [comment]
Reproduced on windows 10, latest chrome ✅

**Comment by muryoh** [comment]
This is already fixed and released :smile:
