### ISSUE TITLE
Error message after deleting a design system

### ISSUE THREAD

**Issue by kaelig** [divriots/backlight.dev#25]
### 📖 Reproduction steps

Delete an existing design system.

### 🙁 Current Behavior

![image](https://user-images.githubusercontent.com/85783/156826945-9f3cc1ae-53f0-4d81-bb2a-62de667551e6.png)

### 🙂 Expected Behavior

A message that confirms the design system was deleted, with a link to return to the homepage (for example).

### 🌐 What browser(s) are you seeing the problem on?

Chrome

**Comment by muryoh** [comment]
Will be fixed in next release!
