### ISSUE TITLE
npm publish failing (running out of memory)

### ISSUE THREAD

**Issue by deanlot** [divriots/backlight.dev#27]
### 📖 Reproduction steps

1. Go to 'Release'
2. Click on 'publish'

### 🙁 Current Behavior

the npm build animation does not change into the npm package repo link. It stays animating.

After @gqio and I looked, the process seems to be running out of memory, and GC is failing.

### 🙂 Expected Behavior

the package should be published correctly to our npm repo.

### 🔗 Link to the design system

https://backlight.dev/review/1cSXPvoh70elNHaKHeGj/components/button/src/Button.styles.ts?p=stories

### 🌐 What browser(s) are you seeing the problem on?

Chrome

### Browser version(s)

99.0.4844.51

**Comment by muryoh** [comment]
Fixed and released yesterday :tada: 
(increased the available memory on release process)
