### ISSUE TITLE
I am unable to try this out as the page is stuck on "Initializing compilation toolchain"

### ISSUE THREAD

**Issue by wardourdigital** [divriots/backlight.dev#31]
### 📖 Reproduction steps

Create a new project

### 🙁 Current Behavior

Screen stuck on: Initializing compilation toolchain

### 🙂 Expected Behavior

I guess to progress past: Initializing compilation toolchain

### 🌐 What browser(s) are you seeing the problem on?

Safari

### Browser version(s)

Safari - Version 15.4 (17613.1.17.1.6)

**Comment by muryoh** [comment]
Hi @wardourdigital - sorry to hear that

We are unfortunately limited in our browser support as Safari doesn't implement all features we need or just not in a way that works for us
Could you give it a try with Chrome or Firefox?
If it doesn't work, be sure to provide a link to the design system which isn't working so we can have a look

Cheers! :pray:

**Comment by wardourdigital** [comment]
Ah yes. Safari, slowly becoming the IE of the modern dev world. FF works. Thanks.
