### ISSUE TITLE
Illegible checkmark icon on backlight highlight color (yellow)

### ISSUE THREAD

**Issue by jorenbroekema** [divriots/backlight.dev#8]
### Reproduction steps

1. Go to backlight.dev
2. create new branch on anything
3. create new component
4. rename component
5. see the icon

### Current Behavior

![image](https://user-images.githubusercontent.com/36734656/131855140-911bf505-db2b-4805-8ccc-63a1075569f3.png)

The checkmark icon is not legible.

### Expected Behavior

Checkmark to have better contrast with the background color (yellow)

### What browser(s) are you seeing the problem on?

Chrome

**Comment by muryoh** [comment]
Fixed in latest versions
![2021-09-27_22-58](https://user-images.githubusercontent.com/1789748/134984313-7b2c73a2-cec3-4499-8744-81d04f58b81b.png)
